name = "jsp000598"
version = "0.1.0"
defaultTargets = ["Jsp000598"]

[[lean_lib]]
name = "Jsp000598"

[[require]]
name = "mathlib"
git = "https://github.com/leanprover-community/mathlib4"
rev = "v4.34.0"
